# Generated by Django 3.2.9 on 2021-12-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_datatest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('secondName', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Csv',
        ),
    ]
