# Generated by Django 3.2.9 on 2021-12-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
